#!/bin/bash

cd $(dirname ${0})
cd ../

file=src/problems.rs

echo "// genarate by tools/genrs" > $file
echo ""                          >> $file

count=0
for i in $(ls *.rs); do
    echo "#[path = \"../$i\"]"  >> $file
    echo "mod mod_${count};"    >> $file
    echo ""                     >> $file
    ((count++))
done

